services:
  - type: web
    name: sai-bhavani-stores
    env: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"